import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, setDoc, getDoc, getDocs, collection, query, where, serverTimestamp, deleteDoc } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'hearth-ae2e0', firestore: { rules: readFileSync(new URL('../docs/firestore.rules', import.meta.url), 'utf8'), host: '127.0.0.1', port: 8085 } });
await env.clearFirestore();
const ctx = (uid, email) => env.authenticatedContext(uid, { email, email_verified: true }).firestore();
const dm = ctx('dmUid', 'dm@example.com'), pl = ctx('plUid', 'Player@Example.com'), eve = ctx('eveUid', 'eve@example.com');
const unverified = env.authenticatedContext('unv', { email: 'player@example.com', email_verified: false }).firestore();
const anon = env.unauthenticatedContext().firestore();
let pass = 0, fail = 0;
async function t(name, p) { try { await p; console.log('PASS', name); pass++; } catch (e) { console.log('FAIL', name, e.message.slice(0, 160)); fail++; } }
const ch = (id, extra = {}) => ({ id, ed: '5e', updatedAt: Date.now(), deleted: false, data: JSON.stringify({ id, name: 'A' }), name: 'A', v: 1, ...extra });
await t('own character write', assertSucceeds(setDoc(doc(pl, 'users/plUid/characters/c1'), ch('c1'))));
await t('own character read', assertSucceeds(getDoc(doc(pl, 'users/plUid/characters/c1'))));
await t('other user cannot read', assertFails(getDoc(doc(eve, 'users/plUid/characters/c1'))));
await t('other user cannot write', assertFails(setDoc(doc(eve, 'users/plUid/characters/c2'), ch('c2'))));
await t('signed-out cannot read', assertFails(getDoc(doc(anon, 'users/plUid/characters/c1'))));
await t('extra field rejected', assertFails(setDoc(doc(pl, 'users/plUid/characters/c3'), ch('c3', { evil: 1 }))));
await t('id mismatch rejected', assertFails(setDoc(doc(pl, 'users/plUid/characters/c4'), ch('c5'))));
await t('oversize data rejected', assertFails(setDoc(doc(pl, 'users/plUid/characters/c6'), ch('c6', { data: 'x'.repeat(900001) }))));
await t('bad edition rejected', assertFails(setDoc(doc(pl, 'users/plUid/characters/c7'), ch('c7', { ed: '4e' }))));
await t('tombstone ok', assertSucceeds(setDoc(doc(pl, 'users/plUid/characters/c1'), ch('c1', { deleted: true, data: '', name: '' }))));
await t('tombstone with data rejected', assertFails(setDoc(doc(pl, 'users/plUid/characters/c1'), ch('c1', { deleted: true }))));
await t('user root doc closed', assertFails(setDoc(doc(pl, 'users/plUid'), { a: 1 })));
const game = (extra = {}) => ({ owner: 'dmUid', ownerName: 'DM', name: 'Game 1', invited: ['player@example.com'], code: 'HEARTH-7KQ3', live: true, updatedAt: serverTimestamp(), ...extra });
await t('DM can read own not-yet-created game doc', assertSucceeds(getDoc(doc(dm, 'games/dmUid_g1'))));
await t('others cannot read a missing game doc', assertFails(getDoc(doc(eve, 'games/dmUid_g1'))));
await t('DM creates game', assertSucceeds(setDoc(doc(dm, 'games/dmUid_g1'), game())));
await t('DM cannot create under another uid prefix', assertFails(setDoc(doc(dm, 'games/eveUid_g1'), game())));
await t('cannot create game owned by someone else', assertFails(setDoc(doc(eve, 'games/eveUid_g2'), game())));
await t('client timestamp rejected', assertFails(setDoc(doc(dm, 'games/dmUid_g3'), game({ updatedAt: new Date() }))));
await t('bad code rejected', assertFails(setDoc(doc(dm, 'games/dmUid_g4'), game({ code: '<script>' }))));
await t('>50 invites rejected', assertFails(setDoc(doc(dm, 'games/dmUid_g5'), game({ invited: Array.from({ length: 51 }, (_, i) => i + '@x.com') }))));
await t('invited player (any email case) reads game', assertSucceeds(getDoc(doc(pl, 'games/dmUid_g1'))));
await t('invited query (array-contains own email)', assertSucceeds(getDocs(query(collection(pl, 'games'), where('invited', 'array-contains', 'player@example.com')))));
await t('uninvited cannot read', assertFails(getDoc(doc(eve, 'games/dmUid_g1'))));
await t('unverified email cannot read', assertFails(getDoc(doc(unverified, 'games/dmUid_g1'))));
await t('list all games denied', assertFails(getDocs(collection(pl, 'games'))));
await t('player cannot edit game', assertFails(setDoc(doc(pl, 'games/dmUid_g1'), game({ invited: ['player@example.com', 'x@y.com'] }))));
const join = (extra = {}) => ({ uid: 'plUid', email: 'player@example.com', name: 'P', deviceId: 'dabcdefghijk123456', nonce: 'abcdefghijklmnop1234', code: 'HEARTH-7KQ3', at: serverTimestamp(), ...extra });
await t('invited player writes own join note', assertSucceeds(setDoc(doc(pl, 'games/dmUid_g1/joins/plUid'), join())));
await t('join note with someone else\'s email rejected', assertFails(setDoc(doc(pl, 'games/dmUid_g1/joins/plUid'), join({ email: 'dm@example.com' }))));
await t('uninvited cannot write join', assertFails(setDoc(doc(eve, 'games/dmUid_g1/joins/eveUid'), join({ uid: 'eveUid', email: 'eve@example.com' }))));
await t('cannot write join for another uid', assertFails(setDoc(doc(eve, 'games/dmUid_g1/joins/plUid'), join())));
await t('DM reads join note', assertSucceeds(getDoc(doc(dm, 'games/dmUid_g1/joins/plUid'))));
await t('other user cannot read join note', assertFails(getDoc(doc(eve, 'games/dmUid_g1/joins/plUid'))));
await t('DM deletes game', assertSucceeds(deleteDoc(doc(dm, 'games/dmUid_g1'))));
console.log(`\n${pass}/${pass + fail} rules tests passed`);
await env.cleanup();
process.exit(fail ? 1 : 0);
